TeamZziririt/zziririt-back

.github/ISSUE_TEMPLATE/-bug-jirakey--bug-제목.md, .github/ISSUE_TEMPLATE/-feature-jirakey--할일-제목.md
1. Create new Feature Issue Template
2. Create new Bug Issue Template
=> [Docs] ZRR-44: Update issue templates

src/main/kotlin/kr/zziririt/zziririt/global/exception/CustomException.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/ModelNotFoundException.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/RestApiException.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/dto/ErrorResponse.kt
1. GlobalExceptionHandler 작성
2. 최상위 예외 Abstract Class인 CustomException 작성
3. 공통 예외 처리할 RestApiException 작성
4. 커스텀 예외 예시 ModelNotFoundException 작성
5. 공통 ErrorCode Enum Class 작성
6. ErrorResponse 작성
자세한 문서 명세는 다음 Notion 링크 참조
[프로젝트 개발 정책 컨벤션](https://moveuk.notion.site/bc1b6aa612504c489931900b0fb18f18?pvs=4)
=> ZRR-46 Add: 공통 예외 처리 핸들러 작성

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepository.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/SecurityConfig.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationToken.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtDto.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtProvider.kt, src/main/resources/application.yml
불필요 클래스, 코드 삭제 완료
API 테스트 완료 ( 네이버 로그인 인증 후 Response와 내용 DB 저장됨 확인)
=> ZRR-4 Feat: Spirng Security 네이버 로그인 API 개발

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepository.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/SecurityConfig.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationToken.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtDto.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtProvider.kt, src/main/resources/application.yml
API 테스트 및 정상 response 확인,
response 데이터 DB 저장 확인
=> ZRR-4 Feat: 네이버 소셜 로그인 API 개발

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt, src/main/kotlin/kr/zziririt/zziririt/infra/aws/S3Config.kt, src/main/kotlin/kr/zziririt/zziririt/infra/aws/S3Service.kt, src/main/kotlin/kr/zziririt/zziririt/infra/aws/UploadHelper.kt, src/main/resources/application.yml
png, jpeg, jpg 파일만 업로드 가능하도록 개발
=> ZRR-47 Feat: s3 이미지 업로드 기능 구현

src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepository.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/SecurityConfig.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/UserPrincipal.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationToken.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtDto.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtProvider.kt, src/main/resources/application.yml
필수 정보만 저장하기 (이메일, 닉네임)
JwtProvider 내 오탈자 수정 accessToken, refreshToken 분리 필요
JWT 인증 불가한 부분 수정
API테스트 완료, 토큰 검증 완료
토큰 검증
=> ZRR-50 Fix: Spring Security OAuth2 네이버 소셜 로그인 코드 수정

src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/repository/SocialMemberRepository.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/OAuthLoginController.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/SecurityConfig.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/UserPrincipal.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationToken.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtDto.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtProvider.kt, src/main/resources/application.yml
필수 정보만 저장하기 (이메일, 닉네임)
JwtProvider 내 오탈자 수정 accessToken, refreshToken 분리 필요
JWT 인증 불가한 부분 수정
API테스트 완료, 토큰 검증 완료
토큰 검증
=> ZRR-50 Fix: Jwt 인증 불가한 현상 수정

src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/CreateFaqRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/FaqResponse.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/UpdateFaqRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/faq/model/FaqEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/faq/repository/FaqRepository.kt
설명: CS에서 FAQ 코드중 CREATE 개발
TODO
=> ZRR-32 Feat: FAQ Create 작성

src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/CreateFaqRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/FaqResponse.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/faq/model/FaqEntity.kt
1. CreateFaqRequest: toFaqEntity 메소드작성
2.컨트롤러 createFaq: @RequestBody createFaqRequest: CreateFaqRequest 변경
3.FaqEntity: toResponse 삭제.
4.FaqResponse: from 메소드 작성.
5.FaqService: createFaq 메소드 작성.
=> ZRR-32 Refactor: FAQ Create 코드리뷰의존결합 낮춤

src/main/kotlin/kr/zziririt/zziririt/global/AppStatusRunner.kt, src/main/resources/application.yml
1. Application.yml 분리 - local, dev, prod: 3 level
2. Server 시작 상태 로깅을 위한 AppStatusRunner 작성
=> ZRR-21 Add: Application.yml 분리 및 Server 시작 상태 확인을 위한 AppRunner 작성

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/api/post/controller/PostController.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/PostSearchCondition.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/SearchType.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/request/CreatePostRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/request/UpdatePostRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/response/PostResponse.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/valid/SearchTypeValidation.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/post/model/PostEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepository.kt, src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepositoryImpl.kt, src/main/kotlin/kr/zziririt/zziririt/infra/jpa/post/PostJpaRepository.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/QueryDslSupport.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepository.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepositoryImpl.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/dto/PostRowDto.kt
1. 글 작성
- 비밀 글 설정 가능
- validation 완료
- ![image](https://github.com/TeamBDMJ/Zziririt/assets/84966961/bca9cbe4-d013-4616-8625-75be6700d4ec)
2. 글 수정
- 비밀 글 설정 가능
- 본인인 경우에만 수정가능(추후 관리자, 스트리머, 보드 관리자의 경우 권한이 존재할 때 변경하도록 개선 필요)
- validation 완료
- ![image](https://github.com/TeamBDMJ/Zziririt/assets/84966961/bc40fdec-bceb-4f1f-858d-bcae7f701fec)
3. 글 삭제
- 본인인 경우에만 수정가능(추후 관리자, 스트리머, 보드 관리자의 경우 권한이 존재할 때 변경하도록 개선 필요)
4. 글 조회
- 글 단건 조회
- 글 목록 조회 +@ 검색 기능
- validation 완료
- ![image](https://github.com/TeamBDMJ/Zziririt/assets/84966961/66a1529b-410a-4427-ad08-9efa69f530d5)
#1 
1. build.gradle.kts: queryDSL 의존성 추가
3. CreatePostRequest: 글 작성을 위한 Dto 추가 - validation 작성
6. PostController: CRUD api 추가 - 글 조회(단건, 목록 검색) - 글 작성 - 글 수정 - 글 삭제
7. PostEntity: 엔티티 수정
8. PostJpaRepository 작성
9. …
=> ZRR-3 Feat: Post 기본 CRUD api 추가

src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/UpdateFaqRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
1. FaqController: updateFaq 메소드 작성.
2.FaqService: updateFeq 메소드 작성.
3.UpdateFaqRequest: UpdateFaqRequest 작성.
4.FaqRepository: FaqRepository작성.
=> ZRR-52 Feat: FAQ Update 코드작성

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/api/member/controller/MemberController.kt, src/main/kotlin/kr/zziririt/zziririt/api/member/dto/request/AdjustRoleRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/member/dto/request/SetBoardManagerRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/member/dto/response/GetMemberResponse.kt, src/main/kotlin/kr/zziririt/zziririt/api/member/service/MemberService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/model/MemberStatus.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt, src/main/kotlin/kr/zziririt/zziririt/global/exception/ErrorCode.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/CustomOAuth2UserService.kt, src/main/kotlin/kr/zziririt/zziririt/infra/security/jwt/JwtAuthenticationFilter.kt, src/main/resources/application.yml
#32 
***
***
1. MemberController: 멤버 관련 API
- 본인 정보 조회
- (관리자 전용) 멤버 권한 조정
- (관리자, 스트리머 전용) 게시판 관리자 임명
- (관리자, 스트리머 전용) 게시판 관리자 해임
2. AdjustRoleRequest : 변경 권한 요청
- Validation 적용
3. GetMemberResponse : 유저 정보 반환
4. MemberService : API 로직 작성
5. MemberStatus : Member의 현재 상태에를 조정함 (일반, 휴면, 정지 상태)
6. SocialMemberEntity
- Enumerated 추가
- Ban 상태 값 추가
- Ban 관련 내용은 Report API 추가 후 관련 Entity로 이전할 예정
=> ZRR-60 Feat: 회원 등급 조정 API 개발

src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt, src/main/kotlin/kr/zziririt/zziririt/api/comment/controller/CommentController.kt, src/main/kotlin/kr/zziririt/zziririt/api/comment/dto/CommentDto.kt, src/main/kotlin/kr/zziririt/zziririt/api/comment/service/CommentService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/comment/model/CommentEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/comment/repository/CommentRepository.kt
***
#4
***
1. CommentController: 댓글 CRUD api, 좋아요(찌릿) 기능
2. CommentDto: 댓글 생성과 수정을 위한 Dto 추가
3. CommentEntity: board_id -> post_id 수정
4. CommentRepository: 파일 위치 변경
5. CommentService: 댓글 CRUD 로직 작성
6. BoardController: valid 어노테이션 위치 변경
=> ZRR-43 Feat: 댓글 기본 CURD API 개발

.github/workflows/backend-build-test.yml
1. main, dev pr merge시 ci test
2. java 17 환경 테스트
3. gradle 캐싱
4. Publish test result
=> ZRR-58 Chore: CI 환경 구성

src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
1.FaqController:deleteFaq 코드 작성.
2.FaqService:deleteFaq 코드 작성.
=> ZRR-59 Feat: FAQ Delete API 개발

src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
1.FaqController: FAQ getFaqs 메소드 작성.
2.FaqServic: FAQ getFaqs 메소드 작성.
=> ZRR-62 Feat: FAQ 목록조회 API 개발.

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/api/post/controller/PostController.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/PostSearchCondition.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepository.kt, src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepositoryImpl.kt, src/main/kotlin/kr/zziririt/zziririt/infra/cache/CacheConfig.kt, src/main/kotlin/kr/zziririt/zziririt/infra/cache/CacheType.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepositoryImpl.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/dto/PostRowDto.kt, src/main/kotlin/kr/zziririt/zziririt/infra/redis/RedisConfig.kt, src/main/kotlin/kr/zziririt/zziririt/infra/redis/post/PostSearchCacheRedisRepository.kt, src/main/resources/application.yml
---
#52
---
1. CacheConfig: Cache 설정
2. CacheType: 캐시할 타입설정
3. PostController: 검색 조회시 버저닝
4. PostQueryDslRepositoryImpl: BooleanExpression 적용되지 않는 버그 수정
5. PostRepository: 캐시 관련 메소드 추가
6. PostRepositoryImpl: 캐시 관련 구현체 추가
7. PostRowDto: Redis 직렬화를 위한 Serializable 상속
8. PostSearchCacheRedisRepository: 캐시 관련 기능 구현
9. PostSearchCondition: 조건 관련 키 생성 메서드 추가
10. PostService: 캐싱 관련 기능 추가
11. RedisConfig: Redis 설정 추가
12. application.yml: 환경별 redis 설정 추가
13. Build_gradle.kts: cache 의존성 추가
=> ZRR-67 Feat: 검색기능 캐싱(캐싱별 버저닝)

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/global/AppStatusRunner.kt, src/main/resources/application.yml
---
#55 
---
1. application.yml 및 env파일 최적화
2. build.gradle version hard code 수정
3. AppRunner log 추가
=> ZRR-73 Chore: application.yml 및 env파일 변수명 변경 및build.gradle version 관리 변경

build.gradle.kts
---
#57 
---
1. 0.0.2 version 릴리즈
=> ZRR-75 Release: Zziririt 0.0.2 Version

Dockerfile, src/main/resources/application.yml
---
#63 
---
1. cd를 위한 dockerfile 추가
2. application.yml: test->local로 변수명 변경
=> ZRR-75 Chore: add Dockerfile and update application.yml

build.gradle.kts
---
#57 
---
1. 0.0.2 version 릴리즈
closes #65
=> ZRR-77 Release: Zziririt v0.0.2

Dockerfile, build.gradle.kts, src/main/resources/application.yml
=> 🎉 Zziririt 0.0.2 Release

src/main/kotlin/kr/zziririt/zziririt/api/post/controller/PostController.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/dto/response/PostResponse.kt, src/main/kotlin/kr/zziririt/zziririt/api/post/service/PostService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepository.kt, src/main/kotlin/kr/zziririt/zziririt/domain/post/repository/PostRepositoryImpl.kt, src/main/kotlin/kr/zziririt/zziririt/global/config/MemberAwareAudit.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepository.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/PostQueryDslRepositoryImpl.kt, src/main/kotlin/kr/zziririt/zziririt/infra/querydsl/post/dto/PostRowDto.kt
1. MemberAwareAudit
- anonymousUser의 경우 추가
2. PostController 
- post api 수정 
- 검색 api 수정 
- 게시판 별 page 조회 api 추가 
- 권한 체크 추가
3. PostService 
- post api 수정 
- 검색 api 수정 
- 게시판 별 page 조회 api 추가 
- 권한 체크 로직 추가
4. PostQueryDslRepository 
- 게시판 별 page 조회 api 추가 
- 전체 글 보기 메소드 추가
5. PostQueryDslRepositoryImpl 
- findAll(), findAllByBoardId() 구현 
- 검색시 비밀글은 조회할 수 없도록 조건 추가
6. PostRepository 
- Repository 인터페이스 변경
7. PostRepositoryImpl 
- PostRepositoryImpl 구현 위임 추가
8. PostResponse 
- 게시글 단건 조회시 글에 대한 수정, 권한 삭제 값 추가 
- 정적 메소드 from() -> of() 이름 변경
9. PostRowDto 
- 목록 조회시 읽을 권한에 대한 상태값 추가
Closes #88
=> ZRR-89 Refactor: Post API 스펙 변경

src/main/kotlin/kr/zziririt/zziririt/api/faq/controller/FaqController.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/CreateFaqRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/dto/UpdateFaqRequest.kt, src/main/kotlin/kr/zziririt/zziririt/api/faq/service/FaqService.kt
1.CreateFaqRequest: 제목과 내용 글자수 제한 코드 작성.
2.FaqController: FAQ 어드민권한 코드작성.
3.FaqServic: FAQ 예외 코드 메시지 작성
4.UpdateFaqRequest: 제목과 내용 글자수 제한 코드 작성.
=> ZRR-72 Feat: FAQ-authorization-and-validation

build.gradle.kts
=> ZRR-93 Release: Zziririt v0.1.0🎉

build.gradle.kts, src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt, src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailClient.kt, src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailService.kt, src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailUtility.kt, src/main/kotlin/kr/zziririt/zziririt/infra/oauth2/service/SocialMemberService.kt, src/main/resources/application.yml
연관 티켓
#99 
***
상세 내용
1. JavaMailSender
- 회원가입 시 유저에게 가입 정보에 대한 email 발송
- 재사용성 강화
=> ZRR-99 Feat: JavaMailSender를 사용한 가입 안내 메일 발

src/test/kotlin/kr/zziririt/zziririt/api/faq/service/FaqServiceTest.kt, src/test/kotlin/kr/zziririt/zziririt/domain/faq/model/FaqEntityTest.kt
1.FaqEntityTest: 엔티티 테스트(글생성여부) 확인
2.FaqServiceTest: 서비스중 글 생성기능테스트 확인.
=> ZRR-92 Feat: FAQ-Entity,Service test-code 작성

src/main/kotlin/kr/zziririt/zziririt/api/member/service/MemberService.kt, src/main/kotlin/kr/zziririt/zziririt/api/point/service/PointHistoryService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/model/ChangeDivision.kt, src/main/kotlin/kr/zziririt/zziririt/domain/point/model/PointHistoryEntity.kt, src/main/kotlin/kr/zziririt/zziririt/domain/point/repository/PointHistoryRepository.kt, src/test/kotlin/kr/zziririt/zziririt/api/member/service/MemberServiceTest.kt
#114 
***
1. Point 증/차감 내역 생성 및 관리
- 포인트 증/차감 서비스 로직을 사용할 때 PointHistoryService.regPointHistory 를 통해 PointHistory 에 등록
=> ZRR-101 Feat: Point History

build.gradle.kts, src/main/resources/application.yml
#116 
Prometheus-Grafana Setting
=> ZRR-102 Chore: Prometheus-Grafana Setting

build.gradle.kts
관련 이슈
Closes #120 
이제 진짜 API를 개봉하려합니다!
=> ZRR-104 Release: Zziririt v1.0.0🎉

src/main/resources/application.yml
#125 
---
SMTP.NAME, SMTP.PASSWORD .을 언더바로 수정(_)
=> ZRR-106 Chore: application.yml update

src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailService.kt
#129 
***
###수정 내용
1. MimeMessageHelper 사용
2. addRecipients -> setTo 수정
=> ZRR-107 Bug: MailSender Bug Fix

src/main/kotlin/kr/zziririt/zziririt/api/HealthCheckController.kt, src/main/kotlin/kr/zziririt/zziririt/global/AppStatusRunner.kt, src/main/kotlin/kr/zziririt/zziririt/infra/postgres/DataSourceConfiguration.kt, src/main/kotlin/kr/zziririt/zziririt/infra/postgres/RoutingDataSource.kt, src/main/resources/application.yml
Closes #131 
---
1. application.yml - write, readonly 분리
2. DataSourceConfiguration - CQRS를 위한 설정
3. RoutingDataSource - readonly 속성에 따른 분기 처리
4. AppStatusRunner - DataSource 확인용 Runner 수정
5. HealthCheckController - db connection 체크용 api 추가
=> ZRR-109 Fix: DB CQRS 도입 및 DB AWS RDS Aurora 이전

src/main/kotlin/kr/zziririt/zziririt/api/HealthCheckController.kt, src/main/kotlin/kr/zziririt/zziririt/api/board/controller/BoardController.kt, src/main/kotlin/kr/zziririt/zziririt/api/board/service/BoardService.kt, src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepository.kt, src/main/kotlin/kr/zziririt/zziririt/domain/board/repository/BoardRepositoryImpl.kt, src/main/kotlin/kr/zziririt/zziririt/domain/member/model/SocialMemberEntity.kt, src/main/kotlin/kr/zziririt/zziririt/global/AppStatusRunner.kt, src/main/kotlin/kr/zziririt/zziririt/infra/jpa/board/BoardJpaRepository.kt, src/main/kotlin/kr/zziririt/zziririt/infra/mailsender/MailService.kt, src/main/kotlin/kr/zziririt/zziririt/infra/postgres/DataSourceConfiguration.kt, src/main/kotlin/kr/zziririt/zziririt/infra/postgres/RoutingDataSource.kt, src/main/resources/application.yml
***
#133
*** 
1. BoardController
- updateStreamerApply: Pathvariable 추가
2. BoardRepository
- existsBoardEntityByBoardUrl: 게시판 url 중복 체크 메서드
3. BoardService
- createStreamerBoardApplication, updateStreamerBoardApplication: 게시판 이름, url 중복 체크
- createStreamerBoard: 스트리머 게시판 생성 시 STREAMER 로 멤버롤 변경, 게시판 신청 상태 CREATED 로 변경
=> ZRR-108 Fix: 스트리머 게시판 신청, 생성 리팩토링

src/main/resources/application.yml
Closes #141 
---
1. application.yml - 로그 관련 charset 옵션 설정
=> ZRR-112 Fix: 로그 한글 인코딩 문제 해결을 위한 application.yml 수정

Dockerfile
=> ZRR-118 Chore: RDS DB Scaled Down

build.gradle.kts
ZRR-119 Release: Zziririt v.1.1.2
=> ZRR-119 Release: Zziririt v1.1.2🎉
